rail/fuse/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
   resources :posts

   root "posts#index"

end

rail/fuse/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rail/fuse/app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_attached_file :image, styles: {medium: "700*500#>", small: "350*250>"}
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

rail/fuse/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :posts
end

rail/fuse/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up,keys: [:name])
    end

end

rail/fuse/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  def index
    @posts = Post.all.order("created_at DESC")
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post =current_user.posts.build
  end

  def create
    @post =current_user.posts.build(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private
  def find_post
    @post = Post.find(params[:id])

  end

  def post_params
    params.require(:post).permit(:title, :link, :description, :image)
  end
end

rail/fuse/app/helpers/application_helper.rb
module ApplicationHelper
end

rail/fuse/app/helpers/posts_helper.rb
module PostsHelper
end

rail/fuse/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Fuse</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav id="navigation" >
          <div class="navbar navbar-default topbar" role="navigation"style="background-color: #47D8F8 !important;">
            <div class="container-fluid">
              <div class="navbar-header mob-div">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="navbar-collapse"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
                <a class="navbar-brand external visible-xs"><%=image_tag "aq.jpg", width:"100%" %></a>
              </div>
              <div class="collapse navbar-collapse ">
                <div class="cotainer top-content hidden-sm hidden-xs">
                  <div id="row">
                    <div class="col-lg-2 col-md-2">
                      <!--logo starts-->
                      <a class="navbar-brand"><%=image_tag "aq.jpg", width:"100%" %></a>
                      <!--logo ends-->
                    </div>
                  </div>
                </div>
                <ul class="nav navbar-nav navbar-right "style="color:white">
                     <%if user_signed_in?%>
                           <li class="text-uppercase bor"style="color:white"><%= link_to "Notes"%></li>
                           <li class="text-uppercase bor">  <%= link_to "new Note"%></li>
                           <li class="text-uppercase"><%= link_to "Sign Out", method: :delete%></li>
                     <%else%>
                            <li class="text-uppercase bor"><%= link_to "Log In",new_user_session_path%></li>
                            <li class="text-uppercase"><%= link_to "Sign In",new_user_registration_path%></li>
                      <%end%>

                  </ul>
                </div>
              </div>
            </div>
          </nav>
   </body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
        <%= yield %>
  </body>
</html>

rail/fuse/app/views/posts/_form.html.slim
= simple_form_for @post do |f| 
  = f.input :image
  = f.input :title, lable: "My Fuse"
  = f.input :link 
  = f.input :description 

  = f.button :submit 

rail/fuse/app/views/posts/edit.html.slim
= render 'form'

rail/fuse/app/views/posts/index.html.slim
- @posts.each do |post|
  h2 = link_to post.title,post
  
= link_to "Add New Inspiration", new_post_path

rail/fuse/app/views/posts/new.html.slim
h1 new posts

= render 'form' 

rail/fuse/app/views/posts/show.html.slim
= image_tag @post.image.url(:medium)
h2 =@post.title
h2 =@post.link
h2 =@post.description
h2 =@post.user.name
= link_to "Edit", edit_post_path(@post)
= link_to "Destroy", post_path(@post),method: :delete, data: {confirm: "are you sure?"}
= link_to "Home", root_path