rail/frustro/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  resources :notes
  #authenticate :user do
  #   root 'welcome#index',as: "authenticated_root"
  #end
  root 'welcome#index'

end

rail/frustro/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

rail/frustro/app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
end

rail/frustro/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :notes
end

rail/frustro/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

rail/frustro/app/controllers/notes_controller.rb
class NotesController < ApplicationController
    before_action :find_note, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
    def index
      @notes = Note.where(user_id: current_user)
    end


    def show
    end
    def new
      @note = current_user.notes.build
    end

    def create
      @note = current_user.notes.build(note_params)

       if @note.save
         redirect_to @note
       else
         render 'new'
       end
    end
    def edit
    end

    def update
      if @note.update(note_params)
        redirect_to @note
      else
        render 'edit'
      end
    end

    def destroy
      @note.destroy
      redirect_to notes_path
    end

    private
      def find_note
        @note = Note.find(params[:id])
      end
      def note_params
        params.require(:note).permit(:title,:content)
      end

end

rail/frustro/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

rail/frustro/app/helpers/application_helper.rb
module ApplicationHelper
end

rail/frustro/app/helpers/notes_helper.rb
module NotesHelper
end

rail/frustro/app/helpers/welcome_helper.rb
module WelcomeHelper
end

rail/frustro/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Frustro</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
        <nav id="navigation" >
          <div class="navbar navbar-default topbar" role="navigation"style="background-color: #47D8F8 !important;">
            <div class="container-fluid">
              <div class="navbar-header mob-div">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="navbar-collapse"><span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
                <a class="navbar-brand external visible-xs"><%=image_tag "aq.jpg", width:"100%" %></a>
              </div>
              <div class="collapse navbar-collapse ">
                <div class="cotainer top-content hidden-sm hidden-xs">
                  <div id="row">
                    <div class="col-lg-2 col-md-2">
                      <!--logo starts-->
                      <a class="navbar-brand"><%=image_tag "aq.jpg", width:"100%" %></a>
                      <!--logo ends-->
                    </div>
                  </div>
                </div>
                <ul class="nav navbar-nav navbar-right "style="color:white">
                     <%if user_signed_in?%>
                           <li class="text-uppercase bor"style="color:white"><%= link_to "Notes",notes_path%></li>
                           <li class="text-uppercase bor">  <%= link_to "new Note", new_note_path%></li>
                           <li class="text-uppercase"><%= link_to "Sign Out", destroy_user_session_path, method: :delete%></li>
                     <%else%>
                            <li class="text-uppercase bor"><%= link_to "Log In",new_user_session_path%></li>
                            <li class="text-uppercase"><%= link_to "Sign In",new_user_registration_path%></li>
                      <%end%>

                  </ul>
                </div>
              </div>
            </div>
          </nav>
   </body>
 </html>

           <class=""><p class="notice"><%= notice %></p>
           <p class="alert"><%= alert %></p>

        <%= yield %>

  </body>
</html>

rail/frustro/app/views/notes/_form.html.erb
<div class="form-main">
<%= simple_form_for @note, :html =>{:multipart => true} do |f| %>
  <div id=<%= "box#{@note.id}" -%>>
    <%= f.input :title, lable: "Title"%>
    <%= f.input :content%>
    <%= f.button :submit, :class => 'in-submit' %>
  </div>
<% end %>
</div>

rail/frustro/app/views/notes/_form.html.haml
= simple_form_for @note do |f|
   = f.input :title
   = f.input :content
   = f.button :submit

rail/frustro/app/views/notes/edit.html.erb
<h1> Edit your Note</h1>
<%= render 'form' %>
<%= link_to "cancel", note_path%>

rail/frustro/app/views/notes/index.html.erb
<div class="container" style="height:550px">
  <div class="panel panel-default index" >
      <div class="row">
            <div class="col-lg-5 col-lg-offset-4" >
              <%if @notes.count == 0%>
                 <h1 class="in-h1">There apre no notes for you. But its time to create some.</h1>
              <% else %>
                    <% @notes.each do |note| %>
                     <h2 class="in-h2"><%= link_to  note.title, note%></h2>
                     <p class="in-p"> <%= time_ago_in_words(note.created_at)%></p>
                    <%end%>
              <% end %>
          </div>
       </div>
     </div>
   </div>

rail/frustro/app/views/notes/new.html.erb
<div style="height:550px;">
    <div class="header" style="margin-top:100px;z-index:555">
    <h1 class="text-center"> Add a new note</h1>
    </div>
    <div class="container">
    <%= render 'form' %>
    </div>
</div>

rail/frustro/app/views/notes/show.html.erb
<div class="container" style="height:550px;">
  <div class="panel panel-default show">

    <div class="sh-div"><h2 class="sh-h2">  <%= @note.title%></br></br> </h2></div>

    <div class="sh-div"><p class="sh-p">   <%= @note.content%></br></br></br>  </p></div>

    <button class="btn btn-success">  <%= link_to "Edit",edit_note_path(@note) %></br></button>


    <button class="btn btn-danger">  <%= link_to "delete",note_path(@note),method: :delete, data: {confirm: "Are you sure?"} %></button>


    </div>
  </div>

rail/frustro/app/views/welcome/index.html.erb
<section>
<div class="container">
    <div class="panel panel-default">
        <div class="row " >
              <div class="col-lg-2 col-lg-offset-3">
                  <p>aadii104</p>
              </div>
            </div>
    </div>
</div>
</section>